# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-13 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class1', '0002_auto_20180713_1655'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookinfo',
            table='bookinfo',
        ),
    ]
